=== buha360/IY5AM2_XMLGyak/XMLTaskIY5AM2/IY5AM2XSD.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="Car_IY5AM2" type="CarType">
        <xs:key name="transactionKey">
            <xs:selector xpath=".//Transaction"/>
            <xs:field xpath="@transaction_id"/>
        </xs:key>

        <xs:key name="driverKey">
            <xs:selector xpath=".//Driver"/>
            <xs:field xpath="@driver_id"/>
        </xs:key>

        <xs:keyref name="transactionRef" refer="transactionKey">
            <xs:selector xpath=".//Cars"/>
            <xs:field xpath="@transaction"/>
        </xs:keyref>

        <xs:keyref name="driverRef" refer="driverKey">
            <xs:selector xpath=".//Cars"/>
            <xs:field xpath="@driver"/>
        </xs:keyref>
    </xs:element>

    <!-- CarType Complex Type -->
    <xs:complexType name="CarType">
        <xs:sequence>
            <xs:element name="Transaction" type="TransactionType"/>
            <xs:element name="Cars" type="CarsType"/>
            <xs:element name="Driver" type="DriverType"/>
            <xs:element name="Customer" type="CustomerType"/>
            <xs:element name="Admin" type="AdminType"/>
            <xs:element name="Approving" type="ApprovingType"/>
        </xs:sequence>
    </xs:complexType>

    <!-- TransactionType Complex Type -->
    <xs:complexType name="TransactionType">
        <xs:sequence>
            <xs:element name="transaction_name" type="xs:string"/>
            <xs:element name="transaction_date" type="xs:date"/>
            <xs:element name="transaction_data" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="transaction_id" type="xs:integer" use="required"/>
    </xs:complexType>

    <!-- CarsType Complex Type -->
    <xs:complexType name="CarsType">
        <xs:sequence>
            <xs:element name="car_modell" type="xs:string"/>
            <xs:element name="rent_price" type="xs:decimal"/>
            <xs:element name="car_number" type="xs:string"/>
            <xs:element name="car_status" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="car_id" type="xs:integer" use="required"/>
        <xs:attribute name="transaction" type="xs:integer" use="required"/>
        <xs:attribute name="driver" type="xs:integer" use="required"/>
    </xs:complexType>

    <!-- DriverType Complex Type -->
    <xs:complexType name="DriverType">
        <xs:sequence>
            <xs:element name="phone_number" type="xs:string"/>
            <xs:element name="gender" type="xs:string"/>
            <xs:element name="address" type="AddressType"/>
            <xs:element name="name" type="NameType"/>
        </xs:sequence>
        <xs:attribute name="driver_id" type="xs:integer" use="required"/>
    </xs:complexType>

    <!-- CustomerType Complex Type -->
    <xs:complexType name="CustomerType">
        <xs:sequence>
            <xs:element name="gender" type="xs:string"/>
            <xs:element name="age" type="xs:integer"/>
            <xs:element name="cust_email" type="xs:string"/>
            <xs:element name="address" type="AddressType"/>
            <xs:element name="name" type="NameType"/>
        </xs:sequence>
        <xs:attribute name="customer_id" type="xs:integer" use="required"/>
        <xs:attribute name="transaction" type="xs:integer" use="required"/>
    </xs:complexType>

    <!-- AdminType Complex Type -->
    <xs:complexType name="AdminType">
        <xs:sequence>
            <xs:element name="gender" type="xs:string"/>
            <xs:element name="age" type="xs:integer"/>
            <xs:element name="admin_email" type="xs:string"/>
            <xs:element name="address" type="AddressType"/>
            <xs:element name="name" type="NameType"/>
        </xs:sequence>
        <xs:attribute name="admin_id" type="xs:integer" use="required"/>
    </xs:complexType>

    <!-- ApprovingType Complex Type -->
    <xs:complexType name="ApprovingType">
        <xs:sequence>
            <xs:element name="verification_date" type="xs:date"/>
        </xs:sequence>
        <xs:attribute name="approving_id" type="xs:integer" use="required"/>
        <xs:attribute name="admin" type="xs:integer" use="required"/>
        <xs:attribute name="transaction" type="xs:integer" use="required"/>
    </xs:complexType>

    <!-- AddressType Complex Type -->
    <xs:complexType name="AddressType">
        <xs:sequence>
            <xs:element name="post_code" type="xs:string"/>
            <xs:element name="city" type="xs:string"/>
            <xs:element name="street" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <!-- NameType Complex Type -->
    <xs:complexType name="NameType">
        <xs:sequence>
            <xs:element name="first_name" type="xs:string"/>
            <xs:element name="last_name" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

</xs:schema>

=== buha360/IY5AM2_XMLGyak/XMLTaskIY5AM2/IY5AM2XML_WRITE.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<Car_IY5AM2 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="IY5AM2XSD.xsd">
        
    <Transaction transaction_id="1">
                
        <transaction_name>Tesómnak</transaction_name>
                
        <transaction_date>2023-11-14</transaction_date>
                
        <transactions>
                        
            <transaction_data>Cash</transaction_data>
                    
        </transactions>
            
    </Transaction>
        
    <Transaction transaction_id="2">
                
        <transaction_name>Üzleti</transaction_name>
                
        <transaction_date>2023-11-15</transaction_date>
                
        <transactions>
                        
            <transaction_data>Bank Transfer</transaction_data>
                    
        </transactions>
            
    </Transaction>
        
    <Transaction transaction_id="3">
                
        <transaction_name>Születésnapi Ajándék</transaction_name>
                
        <transaction_date>2023-11-16</transaction_date>
                
        <transactions>
                        
            <transaction_data>Credit Card</transaction_data>
                    
        </transactions>
            
    </Transaction>
        
    <Cars car_id="1" driver="1" transaction="1">
                
        <car_modell>Opel</car_modell>
                
        <rent_price>200.0</rent_price>
                
        <car_number>69</car_number>
                
        <car_status>Available</car_status>
            
    </Cars>
        
    <Cars car_id="3" driver="3" transaction="2">
                
        <car_modell>Toyota</car_modell>
                
        <rent_price>150.0</rent_price>
                
        <car_number>33</car_number>
                
        <car_status>Unavailable</car_status>
            
    </Cars>
        
    <Cars car_id="4" driver="2" transaction="3">
                
        <car_modell>BMW</car_modell>
                
        <rent_price>300.0</rent_price>
                
        <car_number>44</car_number>
                
        <car_status>Available</car_status>
            
    </Cars>
        
    <Driver driver_id="1">
                
        <phone_number>06501311010</phone_number>
                
        <gender>Male</gender>
                
        <post_code>3534</post_code>
                
        <city>Miskolc</city>
                
        <street>Árpád</street>
                
        <first_name>Buha</first_name>
                
        <last_name>Milán</last_name>
            
    </Driver>
        
    <Driver driver_id="2">
                
        <phone_number>06502223344</phone_number>
                
        <gender>Male</gender>
                
        <post_code>1122</post_code>
                
        <city>Debrecen</city>
                
        <street>Kossuth</street>
                
        <first_name>Szabó</first_name>
                
        <last_name>László</last_name>
            
    </Driver>
        
    <Driver driver_id="3">
                
        <phone_number>06505556677</phone_number>
                
        <gender>Female</gender>
                
        <post_code>2045</post_code>
                
        <city>Törökbálint</city>
                
        <street>Fő</street>
                
        <first_name>Nagy</first_name>
                
        <last_name>Anna</last_name>
            
    </Driver>
        
    <Customer customer_id="1" transaction="1">
                
        <gender>Female</gender>
                
        <age>20</age>
                
        <cust_email>barbara@gmail.com</cust_email>
                
        <post_code>3535</post_code>
                
        <city>Miskolc</city>
                
        <street>Kuruc</street>
                
        <first_name>Valaki</first_name>
                
        <last_name>Barbara</last_name>
            
    </Customer>
        
    <Customer customer_id="2" transaction="2">
                
        <gender>Male</gender>
                
        <age>30</age>
                
        <cust_email>istvan@gmail.com</cust_email>
                
        <post_code>6000</post_code>
                
        <city>Kecskemét</city>
                
        <street>Petőfi</street>
                
        <first_name>István</first_name>
                
        <last_name>Szabó</last_name>
            
    </Customer>
        
    <Customer customer_id="3" transaction="3">
                
        <gender>Female</gender>
                
        <age>25</age>
                
        <cust_email>eszter@gmail.com</cust_email>
                
        <post_code>6722</post_code>
                
        <city>Szeged</city>
                
        <street>József</street>
                
        <first_name>Eszter</first_name>
                
        <last_name>Kovács</last_name>
            
    </Customer>
        
    <Admin admin_id="1">
                
        <gender>Male</gender>
                
        <age>32</age>
                
        <admin_email>admin@gmail.com</admin_email>
                
        <post_code>3634</post_code>
                
        <city>Valahol</city>
                
        <street>Napfény</street>
                
        <first_name>Kiss</first_name>
                
        <last_name>János</last_name>
            
    </Admin>
        
    <Admin admin_id="2">
                
        <gender>Female</gender>
                
        <age>28</age>
                
        <admin_email>admin2@gmail.com</admin_email>
                
        <post_code>7632</post_code>
                
        <city>Pécs</city>
                
        <street>Hunyadi</street>
                
        <first_name>Tóth</first_name>
                
        <last_name>Krisztina</last_name>
            
    </Admin>
        
    <Admin admin_id="3">
                
        <gender>Male</gender>
                
        <age>40</age>
                
        <admin_email>admin3@gmail.com</admin_email>
                
        <post_code>1012</post_code>
                
        <city>Budapest</city>
                
        <street>Vár</street>
                
        <first_name>Varga</first_name>
                
        <last_name>Mihály</last_name>
            
    </Admin>
        
    <Approving admin="1" approving_id="1" transaction="1">
                
        <verification_date>2023-11-14</verification_date>
            
    </Approving>
        
    <Approving admin="2" approving_id="2" transaction="2">
                
        <verification_date>2023-11-15</verification_date>
            
    </Approving>
        
    <Approving admin="3" approving_id="3" transaction="3">
                
        <verification_date>2023-11-16</verification_date>
            
    </Approving>
    
</Car_IY5AM2>

=== buha360/IY5AM2_XMLGyak/XMLTaskIY5AM2/IY5AM2XML.xml
<?xml version="1.0" encoding="UTF-8"?>

<Car_IY5AM2 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="IY5AM2XSD.xsd">

    <Transaction transaction_id="1">
        <transaction_name>Tesomnak</transaction_name>
        <transaction_date>2023-11-14</transaction_date>
        <transaction_data>Cash</transaction_data>
    </Transaction>

    <Cars car_id="1" transaction="1" driver="1">
        <car_modell>Opel</car_modell>
        <rent_price>200.0</rent_price>
        <car_number>69</car_number>
        <car_status>Available</car_status>
    </Cars>

    <Driver driver_id="1">
        <phone_number>06501311010</phone_number>
        <gender>Male</gender>
        <address>
            <post_code>3534</post_code>
            <city>Miskolc</city>
            <street>Árpád</street>
        </address>
        <name>
            <first_name>Buha</first_name>
            <last_name>Milán</last_name>
        </name>
    </Driver>

    <Customer customer_id="1" transaction="1">
        <gender>Female</gender>
        <age>20</age>
        <cust_email>barbara@gmail.com</cust_email>
        <address>
            <post_code>3535</post_code>
            <city>Miskolc</city>
            <street>Kuruc</street>
        </address>
        <name>
            <first_name>Valaki</first_name>
            <last_name>Barbara</last_name>
        </name>
    </Customer>

    <Admin admin_id="1">
        <gender>Male</gender>
        <age>32</age>
        <admin_email>admin@gmail.com</admin_email>
        <address>
            <post_code>3634</post_code>
            <city>Valahol</city>
            <street>Napfény</street>
        </address>
        <name>
            <first_name>Kiss</first_name>
            <last_name>János</last_name>
        </name>
    </Admin>

    <Approving approving_id="1" admin="1" transaction="1">
        <verification_date>2023-11-14</verification_date>
    </Approving>

</Car_IY5AM2>
